
 platform :ios, '8.0'

target ‘PointView’ do

pod "AFNetworking"
pod "SDWebImage"
pod "SVProgressHUD"
pod "MJExtension"
pod "MJRefresh"
pod "DACircularProgress"
pod "pop"
pod 'NJKWebViewProgress'
pod 'Masonry'

end
